name: Test JAVA project on different OS

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checks out the repository
        uses: actions/checkout@v2
      - name: Setup Java JDK on ${{ matrix.os }}
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Build with Maven on ${{ matrix.os }}
        run: mvn package